local t = require("tests.harness")
local describe, it, after_each, expect = t.describe, t.it, t.after_each, t.expect

local blob = require("nvim-diff.git.blob")
local errors = require("nvim-diff.git.error")
local files = require("nvim-diff.git.files")
local gitrepo = require("tests.gitrepo")
local repo_mod = require("nvim-diff.git.repo")
local rev = require("nvim-diff.git.rev")

---@param entries NvimDiff.Git.FileChange[]
---@return table<string, NvimDiff.Git.FileChange>
local function by_path(entries)
  local out = {}
  for _, e in ipairs(entries) do
    out[e.path] = e
  end
  return out
end

---@param entries NvimDiff.Git.FileChange[]
---@return string[]
local function summary(entries)
  local out = {}
  for _, e in ipairs(entries) do
    out[#out + 1] = e.status .. " " .. (e.oldpath and (e.oldpath .. " -> ") or "") .. e.path
  end
  return out
end

describe("git files", function()
  after_each(function()
    gitrepo.cleanup()
  end)

  it("lists commit-to-commit changes with stats, renames, binaries and odd names", function()
    local r = gitrepo.new()
    r:write("keep.txt", "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n")
    r:write("gone.txt", "bye\n")
    r:write("mod.txt", "a\nb\n")
    r:write("bin.dat", "x\0y")
    local a = r:commit("a")
    r:git({ "mv", "keep.txt", "moved.txt" })
    r:write("moved.txt", "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n")
    r:delete("gone.txt")
    r:write("mod.txt", "a\nB\nc\n")
    r:write("bin.dat", "x\0z")
    r:write('sp ace/é "q".txt', "new\n")
    local b = r:commit("b")
    local repo = assert(repo_mod.discover(r.root))

    local entries = assert(files.diff(repo, rev.commit(a), rev.commit(b)))
    expect.eq({
      "M bin.dat",
      "D gone.txt",
      "M mod.txt",
      "R keep.txt -> moved.txt",
      'A sp ace/é "q".txt',
    }, summary(entries))

    local e = by_path(entries)
    expect.eq(1, e["moved.txt"].additions)
    expect.eq(0, e["moved.txt"].deletions)
    expect.truthy(e["moved.txt"].similarity >= 50)
    expect.eq(2, e["mod.txt"].additions)
    expect.eq(1, e["mod.txt"].deletions)
    expect.truthy(e["bin.dat"].binary)
    expect.eq(nil, e["bin.dat"].additions)
    expect.eq(0, e["gone.txt"].additions)
    expect.eq(1, e["gone.txt"].deletions)
    expect.eq(40, #e["mod.txt"].new_oid, "object ids are never abbreviated")
    expect.truthy(files.is_zero_oid(e["gone.txt"].new_oid))
    expect.eq("000000", e['sp ace/é "q".txt'].old_mode)
  end)

  it("detects renames even when diff.renames is off", function()
    local r = gitrepo.new()
    r:git({ "config", "diff.renames", "false" })
    r:write("a.txt", "one\ntwo\nthree\n")
    local a = r:commit("a")
    r:git({ "mv", "a.txt", "b.txt" })
    local b = r:commit("b")
    local repo = assert(repo_mod.discover(r.root))
    expect.eq({ "R a.txt -> b.txt" }, summary(assert(files.diff(repo, rev.commit(a), rev.commit(b)))))
  end)

  it("separates staged, unstaged, and untracked changes", function()
    local r = gitrepo.new()
    r:write("a.txt", "a\n")
    r:write("b.txt", "b\n")
    r:commit("base")
    r:write("a.txt", "a2\n")
    r:git({ "add", "a.txt" })
    r:write("b.txt", "b2\n")
    r:write("new.txt", "n\n")
    r:write(".gitignore", "ignored.txt\n")
    r:write("ignored.txt", "i\n")
    local repo = assert(repo_mod.discover(r.root))

    local status = assert(files.status(repo))
    expect.eq({ "M a.txt" }, summary(status.staged))
    expect.eq({ "M b.txt", "? .gitignore", "? new.txt" }, summary(status.unstaged))
    expect.eq({}, status.conflicted)

    local head = assert(rev.head(repo))
    expect.eq({ "M a.txt", "M b.txt" }, summary(assert(files.diff(repo, head, rev.worktree(), { untracked = false }))))
    expect.eq({ "M a.txt" }, summary(assert(files.diff(repo, head, rev.index()))))
  end)

  it("handles an unborn branch by diffing against the empty tree", function()
    local r = gitrepo.new()
    r:write("first.txt", "1\n2\n")
    r:git({ "add", "first.txt" })
    local repo = assert(repo_mod.discover(r.root))
    local status = assert(files.status(repo))
    expect.eq({ "A first.txt" }, summary(status.staged))
    expect.eq(2, status.staged[1].additions)
  end)

  it("reports conflicted paths once, as U", function()
    local r = gitrepo.new()
    r:write("c.txt", "base\n")
    r:commit("base")
    r:git({ "checkout", "-q", "-b", "other" })
    r:write("c.txt", "theirs\n")
    r:commit("theirs")
    r:git({ "checkout", "-q", "main" })
    r:write("c.txt", "ours\n")
    r:commit("ours")
    vim.system({ "git", "merge", "-q", "other" }, { cwd = r.root }):wait()
    local repo = assert(repo_mod.discover(r.root))
    local status = assert(files.status(repo))
    expect.eq({ "c.txt" }, status.conflicted)
    expect.eq({ "U c.txt" }, summary(status.unstaged))
  end)

  it("limits to literal paths", function()
    local r = gitrepo.new()
    r:write("a*.txt", "1\n")
    r:write("ab.txt", "1\n")
    local a = r:commit("a")
    r:write("a*.txt", "2\n")
    r:write("ab.txt", "2\n")
    local b = r:commit("b")
    local repo = assert(repo_mod.discover(r.root))
    local entries = assert(files.diff(repo, rev.commit(a), rev.commit(b), { paths = { "a*.txt" } }))
    expect.eq({ "M a*.txt" }, summary(entries))
  end)

  it("lists a root commit against the empty tree", function()
    local r = gitrepo.new()
    r:write("x.txt", "x\n")
    local root = r:commit("root")
    local repo = assert(repo_mod.discover(r.root))
    local empty = assert(rev.empty(repo))
    expect.eq({ "A x.txt" }, summary(assert(files.diff(repo, empty, rev.commit(root)))))
  end)

  it("rejects a pair git cannot list", function()
    local repo = assert(repo_mod.discover(gitrepo.new().root))
    local _, err = files.diff(repo, rev.worktree(), rev.index())
    expect.truthy(errors.is(err, "invalid"))
  end)
end)

describe("git blob", function()
  after_each(function()
    gitrepo.cleanup()
  end)

  it("reads a path at a commit, the index and the worktree", function()
    local r = gitrepo.new()
    r:write("f.txt", "committed\r\n")
    local c = r:commit("c")
    r:write("f.txt", "staged\n")
    r:git({ "add", "f.txt" })
    r:write("f.txt", "on disk")
    local repo = assert(repo_mod.discover(r.root))

    expect.eq({ bytes = "committed\r\n", binary = false }, blob.read(repo, rev.commit(c), "f.txt"))
    expect.eq("staged\n", assert(blob.read(repo, rev.index(), "f.txt")).bytes)
    expect.eq("on disk", assert(blob.read(repo, rev.worktree(), "./f.txt")).bytes)
  end)

  it("reads a file at a path with spaces, colons and unicode", function()
    local r = gitrepo.new()
    r:write("d i r/a:b é.txt", "odd\n")
    local c = r:commit("c")
    local repo = assert(repo_mod.discover(r.root))
    expect.eq("odd\n", assert(blob.read(repo, rev.commit(c), "d i r/a:b é.txt")).bytes)
  end)

  it("flags binaries by a NUL byte and keeps the bytes exact", function()
    local r = gitrepo.new()
    r:write("b.bin", "a\0b\255")
    local c = r:commit("c")
    local repo = assert(repo_mod.discover(r.root))
    local got = assert(blob.read(repo, rev.commit(c), "b.bin"))
    expect.truthy(got.binary)
    expect.eq("a\0b\255", got.bytes)
  end)

  it("distinguishes a missing path from a directory", function()
    local r = gitrepo.new()
    r:write("dir/x.txt", "x\n")
    local c = r:commit("c")
    local repo = assert(repo_mod.discover(r.root))
    local _, missing = blob.read(repo, rev.commit(c), "nope.txt")
    expect.truthy(errors.is(missing, "not_found"), tostring(missing))
    local _, tree = blob.read(repo, rev.commit(c), "dir")
    expect.truthy(errors.is(tree, "not_a_blob"), tostring(tree))
    local _, gone = blob.read(repo, rev.worktree(), "nope.txt")
    expect.truthy(errors.is(gone, "not_found"))
    local _, dir = blob.read(repo, rev.worktree(), "dir")
    expect.truthy(errors.is(dir, "not_a_blob"))
  end)

  it("reads a conflict's stages", function()
    local r = gitrepo.new()
    r:write("c.txt", "base\n")
    r:commit("base")
    r:git({ "checkout", "-q", "-b", "other" })
    r:write("c.txt", "theirs\n")
    r:commit("theirs")
    r:git({ "checkout", "-q", "main" })
    r:write("c.txt", "ours\n")
    r:commit("ours")
    vim.system({ "git", "merge", "-q", "other" }, { cwd = r.root }):wait()
    local repo = assert(repo_mod.discover(r.root))
    expect.eq("base\n", assert(blob.read(repo, rev.index(1), "c.txt")).bytes)
    expect.eq("ours\n", assert(blob.read(repo, rev.index(2), "c.txt")).bytes)
    expect.eq("theirs\n", assert(blob.read(repo, rev.index(3), "c.txt")).bytes)
  end)

  it("reads a symlink as its target, the way git stores it", function()
    local r = gitrepo.new()
    r:write("target.txt", "t\n")
    vim.uv.fs_symlink("target.txt", r.root .. "/link")
    local c = r:commit("c")
    local repo = assert(repo_mod.discover(r.root))
    expect.eq("target.txt", assert(blob.read(repo, rev.commit(c), "link")).bytes)
    expect.eq("target.txt", assert(blob.read(repo, rev.worktree(), "link")).bytes)
  end)

  it("splits bytes into buffer lines and reports the final newline", function()
    expect.eq({ { "a", "b" }, true }, { blob.lines("a\nb\n") })
    expect.eq({ { "a", "b" }, false }, { blob.lines("a\nb") })
    expect.eq({ { "" }, true }, { blob.lines("\n") })
    expect.eq({ {}, false }, { blob.lines("") })
    expect.eq({ { "a\r" }, true }, { blob.lines("a\r\n") })
  end)
end)
