local t = require("tests.harness")
local describe, it, after_each, expect = t.describe, t.it, t.after_each, t.expect

local fetch = require("nvim-diff.git.fetch")
local gitrepo = require("tests.gitrepo")
local prremote = require("tests.prremote")
local repo_mod = require("nvim-diff.git.repo")

describe("git fetch", function()
  after_each(function()
    prremote.cleanup()
    gitrepo.cleanup()
  end)

  it("fetches a PR's missing commits without writing any ref", function()
    local pr = prremote.new()
    local repo = assert(repo_mod.discover(pr.repo.root))
    local refs_before = pr.repo:git({ "for-each-ref" })
    expect.falsy(fetch.has_commit(repo, pr.head))
    expect.falsy(fetch.has_commit(repo, pr.base))

    expect.eq(true, (fetch.commits(repo, "origin", { "refs/pull/7/head", "refs/heads/main" }, { pr.head, pr.base })))
    expect.truthy(fetch.has_commit(repo, pr.head))
    expect.truthy(fetch.has_commit(repo, pr.base))
    expect.eq(refs_before, pr.repo:git({ "for-each-ref" }))
  end)

  it("does not fetch when every commit is already there", function()
    local pr = prremote.new()
    local repo = assert(repo_mod.discover(pr.repo.root))
    assert(fetch.commits(repo, "origin", { "refs/pull/7/head" }, { pr.head }))
    local fetch_head = repo.gitdir .. "/FETCH_HEAD"
    expect.truthy(vim.uv.fs_stat(fetch_head))
    os.remove(fetch_head)

    assert(fetch.commits(repo, "origin", { "refs/pull/7/head" }, { pr.head, pr.fork_point }))
    expect.falsy(vim.uv.fs_stat(fetch_head), "nothing was fetched")
  end)

  it("reports a ref the remote does not have", function()
    local pr = prremote.new()
    local repo = assert(repo_mod.discover(pr.repo.root))
    local ok, err = fetch.commits(repo, "origin", { "refs/pull/99/head" }, { pr.head })
    expect.falsy(ok)
    expect.eq("failed", err.kind)
  end)

  it("reports a commit that is still missing after the fetch", function()
    local pr = prremote.new()
    local repo = assert(repo_mod.discover(pr.repo.root))
    local nowhere = string.rep("1", #pr.head)
    local ok, err = fetch.commits(repo, "origin", { "refs/pull/7/head" }, { pr.head, nowhere })
    expect.falsy(ok)
    expect.eq("not_found", err.kind)
    expect.matches(nowhere, err.message)
    expect.truthy(fetch.has_commit(repo, pr.head), "what could be fetched was")
  end)

  it("refuses a remote name that reads as an option", function()
    local pr = prremote.new()
    local repo = assert(repo_mod.discover(pr.repo.root))
    local ok, err = fetch.commits(repo, "--upload-pack=touch", { "refs/pull/7/head" }, { pr.head })
    expect.falsy(ok)
    expect.eq("invalid", err.kind)
  end)
end)
