local t = require("tests.harness")
local describe, it, after_each, expect = t.describe, t.it, t.after_each, t.expect

local config = require("nvim-diff.config")
local errors = require("nvim-diff.git.error")
local gitrepo = require("tests.gitrepo")
local job = require("nvim-diff.core.job")
local repo_mod = require("nvim-diff.git.repo")
local rev = require("nvim-diff.git.rev")
local revparse = require("nvim-diff.git.revparse")

describe("git", function()
  after_each(function()
    gitrepo.cleanup()
    config.reset()
  end)

  describe("cmd", function()
    it("puts the lock and quoting flags on every invocation", function()
      local argv = require("nvim-diff.git.cmd").argv({ "status" }, {})
      expect.eq({ "git", "--no-optional-locks", "-c", "core.quotePath=false", "status" }, argv)
      local log_argv = require("nvim-diff.git.cmd").argv({ "log" }, { log = true })
      expect.eq({ "git", "--no-optional-locks", "-c", "core.quotePath=false", "-c", "gc.auto=0", "log" }, log_argv)
    end)

    it("reports a missing git binary as spawn_failed", function()
      local r = gitrepo.new()
      config.setup({ git = { bin = "nvim-diff-no-such-git" } })
      local repo, err = repo_mod.discover(r.root)
      expect.eq(nil, repo)
      expect.truthy(errors.is(err, "spawn_failed"), tostring(err))
    end)
  end)

  describe("repo", function()
    it("discovers the toplevel, gitdir and common dir from a subdirectory", function()
      local r = gitrepo.new()
      r:write("sub/dir/file.txt", "x\n")
      local repo = assert(repo_mod.discover(r.root .. "/sub/dir/file.txt"))
      expect.eq(r.root, repo.toplevel)
      expect.eq(r.root .. "/.git", repo.gitdir)
      expect.eq(r.root .. "/.git", repo.common_dir)
    end)

    it("resolves a linked worktree's common dir to the main .git", function()
      local r = gitrepo.new()
      r:commit("root")
      local linked = r.root .. "-linked"
      r:git({ "worktree", "add", "-q", "--detach", linked })
      local repo = assert(repo_mod.discover(linked))
      r:git({ "worktree", "remove", "--force", linked })
      expect.eq(linked, repo.toplevel)
      expect.eq(r.root .. "/.git", repo.common_dir)
      expect.matches("/%.git/worktrees/", repo.gitdir)
    end)

    it("returns not_a_repository outside a work tree", function()
      local dir = vim.fn.tempname()
      vim.fn.mkdir(dir, "p")
      local repo, err = repo_mod.discover(dir)
      vim.fn.delete(dir, "rf")
      expect.eq(nil, repo)
      expect.truthy(errors.is(err, "not_a_repository"), tostring(err))
    end)

    it("hashes the empty tree", function()
      local repo = assert(repo_mod.discover(gitrepo.new().root))
      expect.eq("4b825dc642cb6eb9a060e54bf8d69288fbee4904", repo_mod.empty_tree(repo))
    end)
  end)

  describe("rev", function()
    it("resolves names to full commit ids, keeping the name as the label", function()
      local r = gitrepo.new()
      local first = r:commit("one")
      r:commit("two")
      local repo = assert(repo_mod.discover(r.root))
      local resolved = assert(rev.resolve(repo, "HEAD~1"))
      expect.eq({ type = "commit", oid = first, label = "HEAD~1" }, resolved)
      expect.eq("HEAD~1", rev.display(resolved))
      expect.eq(first:sub(1, 12), rev.id(resolved))
    end)

    it("peels an annotated tag to its commit", function()
      local r = gitrepo.new()
      local oid = r:commit("one")
      r:git({ "tag", "-a", "-m", "tag", "v1" })
      local repo = assert(repo_mod.discover(r.root))
      expect.eq(oid, assert(rev.resolve(repo, "v1")).oid)
    end)

    it("rejects unknown names, trees and option-looking input as bad_revision", function()
      local r = gitrepo.new()
      r:commit("one")
      local repo = assert(repo_mod.discover(r.root))
      for _, spec in ipairs({ "nope", "HEAD^{tree}", "--all", "" }) do
        local got, err = rev.resolve(repo, spec)
        expect.eq(nil, got, spec)
        expect.truthy(errors.is(err, "bad_revision"), spec .. ": " .. tostring(err))
      end
    end)

    it("reports an unborn HEAD as bad_revision", function()
      local repo = assert(repo_mod.discover(gitrepo.new().root))
      local _, err = rev.head(repo)
      expect.truthy(errors.is(err, "bad_revision"))
    end)

    it("names objects for cat-file", function()
      expect.eq("abc:a/b", rev.object(rev.commit("abc"), "a/b"))
      expect.eq(":0:a", rev.object(rev.index(), "a"))
      expect.eq(":3:a", rev.object(rev.index(3), "a"))
      expect.eq(nil, rev.object(rev.worktree(), "a"))
    end)
  end)

  describe("revparse", function()
    it("parses the three range forms, defaulting an empty side to HEAD", function()
      expect.eq({ mode = "merge_base", left = "main", right = "feature" }, revparse.parse("main...feature"))
      expect.eq({ mode = "tip", left = "main", right = "feature" }, revparse.parse("main..feature"))
      expect.eq({ mode = "merge_base", left = "main", right = "HEAD" }, revparse.parse("main..."))
      expect.eq({ mode = "tip", left = "HEAD", right = "x" }, revparse.parse("..x"))
      expect.eq({ mode = "single", left = "HEAD~2" }, revparse.parse(" HEAD~2 "))
      local _, err = revparse.parse("  ")
      expect.truthy(errors.is(err, "invalid"))
    end)

    it("takes a bare pair's mode from revs.merge_base", function()
      expect.eq("merge_base", revparse.pair("a", "b").mode)
      config.setup({ revs = { merge_base = false } })
      expect.eq("tip", revparse.pair("a", "b").mode)
    end)

    --- main: base -> m1 ; feature: base -> f1
    ---@return Test.Repo, NvimDiff.Git.Repo, table<string, string>
    local function forked()
      local r = gitrepo.new()
      local oids = {}
      r:write("f.txt", "base\n")
      oids.base = r:commit("base")
      r:git({ "checkout", "-q", "-b", "feature" })
      r:write("feature.txt", "f\n")
      oids.f1 = r:commit("f1")
      r:git({ "checkout", "-q", "main" })
      r:write("main.txt", "m\n")
      oids.m1 = r:commit("m1")
      return r, assert(repo_mod.discover(r.root)), oids
    end

    it("resolves a...b against the merge base and a..b tip to tip", function()
      local _, repo, oids = forked()
      local mb = assert(revparse.resolve(repo, "main...feature"))
      expect.eq(oids.base, mb.left.oid)
      expect.eq(oids.f1, mb.right.oid)
      expect.eq("merge-base(main, feature)", mb.left.label)

      local tip = assert(revparse.resolve(repo, "main..feature"))
      expect.eq(oids.m1, tip.left.oid)
      expect.eq(oids.f1, tip.right.oid)
    end)

    it("toggles between the two modes and refuses for a single revision", function()
      local _, repo, oids = forked()
      local mb = assert(revparse.resolve(repo, "main...feature"))
      local tip = assert(revparse.toggle(repo, mb))
      expect.eq("tip", tip.spec.mode)
      expect.eq(oids.m1, tip.left.oid)
      local back = assert(revparse.toggle(repo, tip))
      expect.eq(oids.base, back.left.oid)

      local single = assert(revparse.resolve(repo, "HEAD"))
      expect.eq("worktree", single.right.type)
      local _, err = revparse.toggle(repo, single)
      expect.truthy(errors.is(err, "invalid"))
    end)

    it("swaps a HEAD right side for the worktree only when asked", function()
      local _, repo = forked()
      expect.eq("commit", assert(revparse.resolve(repo, "feature...main")).right.type)
      local implied = assert(revparse.resolve(repo, "feature...main", { imply_local = true }))
      expect.eq("worktree", implied.right.type)
      local other = assert(revparse.resolve(repo, "main...feature", { imply_local = true }))
      expect.eq("commit", other.right.type)
    end)

    it("reports unrelated histories as no_merge_base", function()
      local r, repo = forked()
      r:git({ "checkout", "-q", "--orphan", "lonely" })
      r:commit("unrelated")
      local _, err = revparse.resolve(repo, "main...lonely")
      expect.truthy(errors.is(err, "no_merge_base"), tostring(err))
      expect.truthy(revparse.resolve(repo, "main..lonely"))
    end)

    it("reports the failing side as bad_revision", function()
      local _, repo = forked()
      local _, err = revparse.resolve(repo, "main...nope")
      expect.truthy(errors.is(err, "bad_revision"))
      expect.matches("nope", tostring(err))
    end)

    it("works the same inside a task", function()
      local _, repo, oids = forked()
      local task = job.task(function()
        return revparse.resolve(repo, "main...feature")
      end)
      expect.truthy(task:wait(5000))
      expect.eq(oids.base, task.values[1].left.oid)
    end)
  end)
end)
